### ISSUE TITLE
脚本《哔哩哔哩BILIBILI 美化|增强|自定义背景|评论过滤等》无法打开设置界面

### ISSUE THREAD

**Issue by 20171213** [Yuhanawa/UserScript#5]
两个选项都点过了，点击无任何反应，环境：win10ltsc+Violentmonkey BETAv2.15.10+chrome 118.0.5993.118

**Comment by Yuhanawa** [comment]
已修复，添加了https://yuhanawa.github.io/tools/userscriptconfig/ ，同时现在对三个设置站点进行测速并打开最快的站点
